# Generated by Django 3.0.6 on 2020-05-29 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country_team',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=6)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='match_user',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country1', models.CharField(max_length=200)),
                ('country2', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('match_id', models.IntegerField(default=0)),
                ('captain', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('user_id', 'match_id')},
            },
        ),
        migrations.CreateModel(
            name='match_performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(default=0)),
                ('player_id', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=200)),
                ('runs', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('match_id', 'player_id')},
            },
        ),
        migrations.CreateModel(
            name='choosen_players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('user_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateTeam.user_team')),
            ],
            options={
                'unique_together': {('user_match', 'player_id')},
            },
        ),
    ]
