# Generated by Django 3.0.6 on 2020-05-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('matchid', models.IntegerField(primary_key=True, serialize=False)),
                ('coun1', models.CharField(max_length=20)),
                ('coun2', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('points', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_team',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('captain', models.IntegerField()),
                ('matchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateTeam.Matches')),
            ],
            options={
                'unique_together': {('user_id', 'matchid')},
            },
        ),
        migrations.CreateModel(
            name='Choosen_players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateTeam.Players')),
                ('user_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateTeam.User_team')),
            ],
            options={
                'unique_together': {('user_match', 'pid')},
            },
        ),
    ]
