# Generated by Django 3.0.6 on 2020-05-29 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateTeam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choosen_players',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateTeam.country_team'),
        ),
    ]
